apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: voip
  labels:
    component: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: app
          image: atsip/scaling-ari-app
          env:
            - name: NATS_URI
              value: nats://nats:4222
