apiVersion: v1
kind: Service
metadata:
  name: asterisk
  namespace: voip
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  selector:
    component: asterisk
  ports:
    - name: sip
      protocol: UDP
      port: 5060